# .github/workflows/deploy.yml
name: GCPにデプロイ

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # 環境変数を一箇所で管理
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app
      REGION: us-central1
      SERVICE_NAME: nextjs-app
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3
      
    - name: Node.jsをセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: pnpmをインストール
      uses: pnpm/action-setup@v2
      with:
        version: 10
        
    - name: 依存関係をインストール
      run: pnpm install --frozen-lockfile
      
    - name: リントとテスト
      run: pnpm turbo lint test
      
    - name: ビルド
      run: pnpm turbo build
      
    # GCP認証 - シンプルな形式で
    - name: Google Cloud認証
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    # Google Cloud SDK設定
    - name: Google Cloud SDKをセットアップ
      uses: google-github-actions/setup-gcloud@v1
        
    - name: DockerをGCR用に設定
      run: gcloud auth configure-docker
      
    - name: Dockerイメージをビルドしてプッシュ
      run: |
        docker build -t $IMAGE_NAME -f apps/web/Dockerfile .
        docker push $IMAGE_NAME
        
    # Terraform のリソース設定をコマンドラインオプションに変換
    - name: Cloud Runにデプロイ
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE_NAME \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --set-env-vars="NODE_ENV=production"